#ifndef NETWORK_LIBEVENT_LIB_H
#define NETWORK_LIBEVENT_LIB_H

#include "dios/platform.h"

#ifdef NETWORK_LIBEVENT_AS_DLL
	#if  defined ( NETWORK_LIBEVENT_EXPORT )
	#define NETWORK_LIBEVENT_DECL DS_DLL_EXPORT
	#else
	#define NETWORK_LIBEVENT_DECL DS_DLL_EXPORT
	#endif // NETWORK_LIBEVENT_EXPORT
#else
	#define NETWORK_LIBEVENT_DECL
#endif

#endif // NETWORK_LIBEVENT_LIB_H
